blank_issues_enabled: false
contact_links:
  - name: README & Troubleshooting
    url: https://github.com/PIO-Anurag-Garg/ia-tools-ibmi#troubleshooting
    about: Check the troubleshooting section before filing an issue
